### ISSUE TITLE
Integrate OpenStreetMaps

### ISSUE THREAD

**Issue by henne90gen** [henne90gen/Spover#7]

**Comment by MaX-Lo** [comment]
Seems the parser can't handle responses containing no way elements.(?)

```
E/AndroidRuntime: FATAL EXCEPTION: Thread-12
    Process: de.spover.spover, PID: 6284
    com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class de.spover.spover.network.Osm] value failed for JSON property way due to missing (therefore NULL) value for creator parameter ways which is a non-nullable type
        at [Source: (StringReader); line: 501, column: 1] (through reference chain: de.spover.spover.network.Osm["way"])
        at com.fasterxml.jackson.module.kotlin.KotlinValueInstantiator.createFromObjectWith(KotlinValueInstantiator.kt:107)
        at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:195)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:488)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
        at com.fasterxml.jackson.dataformat.xml.deser.WrapperHandlingDeserializer.deserialize(WrapperHandlingDeserializer.java:113)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
        at de.spover.spover.network.OpenStreetMapsClient.run(OpenStreetMapsClient.kt:91)
        at de.spover.spover.network.OpenStreetMapsClient.access$run(OpenStreetMapsClient.kt:23)
        at de.spover.spover.network.OpenStreetMapsClient$onStartJob$thread$1.run(OpenStreetMapsClient.kt:73)
        at java.lang.Thread.run(Thread.java:764)
```
